# Trigger builds on commits and merges to all branches, excluding specified branches
trigger:
  batch: true
  branches:
    include:
    - '*'
    exclude:
    - main

# Trigger builds on PRs to branch
pr:
  branches:
    include:
    - main

extends:
  template: ./Shared/azure-pipelines.yml